import "./globals.css";
import Header from "./components/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-800">
        <Header />
        <div className="flex items-center justify-center">
          {children}
        </div>
      </body>
    </html>
  );
}

